//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revision
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscription()
        {
            this.Paiements = new HashSet<Paiement>();
            this.Seances = new HashSet<Seance>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<int> duree { get; set; }
        public Nullable<System.DateTime> date_publication { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<int> id_matiere { get; set; }
        public Nullable<int> id_etudiant { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Matiere Matiere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seances { get; set; }
    }
}
