//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revision
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_paiment { get; set; }
        public Nullable<double> montant { get; set; }
        public string imprime { get; set; }
        public Nullable<int> id_inscription { get; set; }
    
        public virtual Inscription Inscription { get; set; }
    }
}
