//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revision
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_seance { get; set; }
        public string masse { get; set; }
        public string valide { get; set; }
        public Nullable<int> id_enseignant { get; set; }
        public Nullable<int> id_inscription { get; set; }
    
        public virtual Enseignant Enseignant { get; set; }
        public virtual Inscription Inscription { get; set; }
    }
}
